name: Release

on:
  push:
      tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
   check-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Update pod file
        run: |
          sed -i '' 's/0.0.7/${{ steps.get_version.outputs.VERSION }}/' ./TestCocoaPods_test_private.podspec
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Updated Podspec file"
          git push

   
